# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Defines a standard way of committing rules and communicating it
brew "commitizen"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# Access GitHub's .gitignore boilerplates
brew "gibo"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Post-modern modal text editor
brew "helix"
# Terminal file manager
brew "lf"
# Postgres C API library
brew "libpq", link: true
# Library for USB device access
brew "libusb"
# List USB devices, just like the Linux lsusb command
brew "lsusb"
# Platform built on V8 to build network applications
brew "node@20"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Contract-oriented programming language
brew "solidity"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash", link: true
# Allows connection to a computer remotely
cask "anydesk"
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Universal database tool and SQL client
cask "dbeaver-community"
# Bitcoin thin client
cask "electrum"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-caskaydia-mono-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-recursive-mono-nerd-font"
# Open Source Multimedia Framework
cask "gstreamer-runtime"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Desktop virtualization software
cask "parallels"
# Collaboration platform for API development
cask "postman"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Open-source code editor
cask "visual-studio-code"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Compatibility layer to run Windows applications
cask "wine-stable"
vscode "damien.autoit"
vscode "genius257.autoit3-debug"
vscode "ms-azuretools.vscode-containers"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "nhoizey.gremlins"
vscode "silverquark.dancehelix"
vscode "sojibahmed.one-dark-night-theme"
