[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "svelte"
formatter = { command = 'prettier', args = ["--parser", "svelte"] }

[[language]]
name = "prisma"
formatter = { command = 'prettier', args = ["--parser", "prisma"] }

[[language]]
name = "toml"
formatter = { command = 'prettier', args = ["--parser", "toml"] }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
  [language.language-server]
  command = "astro-ls"
  args = ["--stdio"]
  [language.config.typescript]
  serverPath = "/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js"
  [language.formatter]
  command = 'prettier'
  args = ["--parser", "astro"]

