[language-server.astro-ls]
  command = "astro-ls"
  args = ["--stdio"]
  # config = { "typescript" = { "tsdk" = "/usr/lib/node_modules/typescript/lib/"}, "environment" = "node" }

[language-server.tailwind-ls]
  command = "tailwindcss-language-server"
  args = ["--stdio"]
  timeout = 5

[language-server.pyright-ls]
  command = "pyright-langserver"
  args = ["--stdio"]
  config = {}

[language-server.typescript-ls]
  command = "typescript-language-server"
  args = ["--stdio"]
  config = { implicitProjectConfiguration = { checkJs = true } }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
language-servers = ["astro-ls", "tailwind-ls"]
formatter = { command = 'pnpm', args = ["prettier", "--parser", "astro"] }

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwind-ls"]
roots = ["svelte.config.js"]
formatter = { command = 'pnpm', args = ["prettier", "--parser", "svelte"] }

[[language]]
name = "javascript"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "typescript"] }
language-servers = ["typescript-ls"]

[[language]]
name = "typescript"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "html"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "html"] }
auto-format = false

[[language]]
name = "css"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "css"] }
auto-format = false

[[language]]
name = "markdown"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "markdown"] }
auto-format = false

[[language]]
name = "json"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "json"] }
auto-format = false

[[language]]
name = "toml"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "toml"] }
auto-format = false

[[language]]
name = "solidity"
formatter = { command = 'pnpm', args = ["prettier", "--parser", "solidity-parse"] }
auto-format = false

[[language]]
name = "python"
auto-format = false
# language-servers = ["pylsp"]

